###当前服务启动的地址
server:
  port: 8000
###  注册到Eureka的服务名称
spring:
  application:
    name: app-xu-member
###    Eurka注册中心的地址
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8100/eureka
      ### 是否注册当前项目为一个服务
    register-with-eureka: true
    ### 去Eureka上获取注册信息
    fetch-registry: true
